const classes=[
 {name:'Pra Mutiara Hati',level:'Prasekolah',icon:'✦',color:'#17c8ff'},
 {name:'Pra Delima Hati',level:'Prasekolah',icon:'●',color:'#0b5cff'},
 {name:'Pra Permata Hati',level:'Prasekolah',icon:'◆',color:'#4938dc'},
 ...Array.from({length:6},(_,i)=>({name:`Tahun ${i+1}`,level:'Sekolah Rendah',icon:String(i+1).padStart(2,'0'),color:['#5aaeff','#0050c8','#17c8ff','#0b5cff','#4938dc','#5aaeff'][i]}))
];
const $=id=>document.getElementById(id);const storeKey=(c,d)=>`skpmkas-attendance-v1:${c}:${d}`;
const state={className:classes[0].name,date:new Date().toLocaleDateString('en-CA'),teacher:'',students:[],timer:null};
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderClasses(){ $('classGrid').innerHTML=classes.map(c=>`<article class="class-card" style="--accent:${c.color}" data-class="${esc(c.name)}"><div class="class-icon">${c.icon}</div><small>${c.level.toUpperCase()}</small><h3>${c.name}</h3><p>Rekod kelas dan kehadiran harian murid.</p><b>Isi kehadiran →</b></article>`).join('');document.querySelectorAll('.class-card').forEach(card=>card.onclick=()=>{state.className=card.dataset.class;$('classSelect').value=state.className;load();location.hash='kehadiran'})}
function init(){renderClasses();$('classSelect').innerHTML=classes.map(c=>`<option>${c.name}</option>`).join('');$('dateInput').value=state.date;$('classSelect').onchange=e=>{state.className=e.target.value;load()};$('dateInput').onchange=e=>{state.date=e.target.value;load()};$('teacherInput').oninput=e=>{state.teacher=e.target.value;scheduleSave()};$('addStudentBtn').onclick=addStudent;$('emptyAddBtn').onclick=addStudent;$('markAllBtn').onclick=()=>{state.students.forEach(s=>s.status='Hadir');renderRows();scheduleSave();toast('Semua murid ditanda hadir')};$('exportBtn').onclick=exportCsv;load()}
function load(){state.students=[];state.teacher='';try{const saved=JSON.parse(localStorage.getItem(storeKey(state.className,state.date))||'null');if(saved){state.students=Array.isArray(saved.students)?saved.students:[];state.teacher=saved.teacher||''}}catch{}$('teacherInput').value=state.teacher;renderRows();updateLabel();$('saveTime').textContent=state.students.length?'Rekod tarikh ini dimuatkan':'Belum ada rekod untuk tarikh ini'}
function addStudent(){state.students.push({id:crypto.randomUUID?crypto.randomUUID():Date.now()+Math.random(),name:'',status:'',note:''});renderRows();scheduleSave();setTimeout(()=>document.querySelector('tbody tr:last-child .name-input')?.focus(),30)}
function renderRows(){const body=$('studentRows');body.innerHTML=state.students.map((s,i)=>`<tr data-id="${s.id}"><td>${i+1}</td><td><input class="name-input" value="${esc(s.name)}" placeholder="Nama penuh murid"></td><td><div class="statuses">${['Hadir','Lewat','Tidak hadir','Cuti / sakit'].map(x=>`<button class="status ${s.status===x?'active':''}" data-status="${x}">${x}</button>`).join('')}</div></td><td><input class="note-input" value="${esc(s.note)}" placeholder="Catatan pilihan"></td><td><button class="remove" title="Padam murid">✕</button></td></tr>`).join('');$('emptyState').style.display=state.students.length?'none':'block';$('studentRows').parentElement.style.display=state.students.length?'table':'none';body.querySelectorAll('tr').forEach((row,i)=>{row.querySelector('.name-input').oninput=e=>{state.students[i].name=e.target.value;scheduleSave()};row.querySelector('.note-input').oninput=e=>{state.students[i].note=e.target.value;scheduleSave()};row.querySelectorAll('.status').forEach(b=>b.onclick=()=>{state.students[i].status=b.dataset.status;renderRows();scheduleSave()});row.querySelector('.remove').onclick=()=>{if(confirm('Padam murid ini daripada senarai kelas?')){state.students.splice(i,1);renderRows();scheduleSave()}}});updateSummary()}
function scheduleSave(){clearTimeout(state.timer);$('saveBadge').classList.add('saving');$('saveBadge').querySelector('b').textContent='Sedang menyimpan…';state.timer=setTimeout(save,450)}
function save(){const payload={className:state.className,date:state.date,teacher:state.teacher,students:state.students,updatedAt:new Date().toISOString()};localStorage.setItem(storeKey(state.className,state.date),JSON.stringify(payload));$('saveBadge').classList.remove('saving');$('saveBadge').querySelector('b').textContent='Semua perubahan disimpan';$('saveTime').textContent=`Disimpan ${new Date().toLocaleTimeString('ms-MY',{hour:'2-digit',minute:'2-digit'})}`;updateSummary();updateLabel()}
function updateSummary(){const counts={'Hadir':0,'Lewat':0,'Tidak hadir':0,'Cuti / sakit':0,'':0};state.students.forEach(s=>counts[s.status]=(counts[s.status]||0)+1);$('countHadir').textContent=counts['Hadir'];$('countLewat').textContent=counts['Lewat'];$('countTidak').textContent=counts['Tidak hadir'];$('countCuti').textContent=counts['Cuti / sakit'];$('countBelum').textContent=counts['']}
function updateLabel(){const date=new Date(state.date+'T00:00:00').toLocaleDateString('ms-MY',{weekday:'long',day:'numeric',month:'long',year:'numeric'});$('recordLabel').textContent=`${state.className} · ${date}`}
function exportCsv(){if(!state.students.length)return toast('Tambah murid sebelum memuat turun');const rows=[['Kelas',state.className],['Tarikh',state.date],['Guru',state.teacher],[],['Bil','Nama murid','Status','Catatan'],...state.students.map((s,i)=>[i+1,s.name,s.status,s.note])];const csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`kehadiran-${state.className.toLowerCase().replaceAll(' ','-')}-${state.date}.csv`;a.click();URL.revokeObjectURL(a.href);toast('Rekod CSV dimuat turun')}
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
init();
